CREATE EXTENSION IF NOT EXISTS CITEXT;

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS forums CASCADE;
DROP TABLE IF EXISTS threads CASCADE;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    nickname CITEXT NOT NULL UNIQUE,
    fullname TEXT NOT NULL,
    email CITEXT NOT NULL UNIQUE,
    about TEXT
);

CREATE TABLE forums (
    id SERIAL PRIMARY KEY,
    slug CITEXT NOT NULL UNIQUE,
    posts INTEGER DEFAULT 0,
    threads INTEGER DEFAULT 0,
    title TEXT NOT NULL,
    username CITEXT REFERENCES users (nickname) NOT NULL
);

CREATE TABLE threads (
    id SERIAL PRIMARY KEY,
    slug CITEXT UNIQUE,
    username CITEXT REFERENCES users (nickname) NOT NULL,
    forum_slug CITEXT REFERENCES forums (slug) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    message TEXT,
    title TEXT NOT NULL UNIQUE,
    votes INTEGER DEFAULT 0
);