CREATE EXTENSION IF NOT EXISTS CITEXT;

DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    nickname CITEXT NOT NULL UNIQUE,
    fullname TEXT NOT NULL,
    email CITEXT NOT NULL UNIQUE,
    about TEXT
);